export default {
  'FORM__ADDRESS_UPDATED': 'FORM__ADDRESS_UPDATED',
  'FORM__ADDRESS_TOGGLE_AUTOCOMPLETE': 'FORM__ADDRESS_TOGGLE_AUTOCOMPLETE',
  'FORM__ADDRESS_UPDATED_PHONE': 'FORM__ADDRESS_UPDATED_PHONE'
}
