export default {
  LOGIN: 'LOGIN',
  FACEBOOK_LOGIN: 'FACEBOOK_LOGIN',
  SET_CURRENT_USER: 'FETCH_CURRENT_USER',
  LOADING: 'LOADING',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  SUBMIT_PROFILE: 'SUBMIT_PROFILE'
}
